apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: blazorpong
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: blazorpong
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: collector
        static_configs:
          - targets: [ 'collector:8889' ]
