apiVersion: v1
kind: Secret
metadata:
  name: azuresql-credentials
  namespace: blazorpong
  labels:
    app.kubernetes.io/name: azuresql
    app.kubernetes.io/part-of: blazorpong
type: Opaque
stringData:
  SA_PASSWORD: "yourStrong(!)Password"
  MSSQL_SA_PASSWORD: "yourStrong(!)Password"
  SIGNALR_CONNECTION_STRING: "Server=azuresql;Database=BlazorpongDB;User=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;Encrypt=False;"
